import Head from "next/head";
import { BsFillMoonStarsFill, BsFillPhoneFill } from "react-icons/bs";
import { RiWhatsappFill } from "react-icons/ri";
import { MdCall } from "react-icons/md";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiOutlineMail,
  AiFillMail,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import nicho from "../public/nicholasorig.png";
import nichodark from "../public/nicholasorig.png";
import bermudez from "../public/workplaces/bermudez.png";
import kaizen from "../public/workplaces/kaizen.png";
import evolve from "../public/workplaces/evolve.png";
import mofe from "../public/workplaces/mofe.png";
import monstermedia from "../public/workplaces/monstermedia.png";
import gg from "../public/workplaces/gg.png";
import uof from "../public/schools/uof.png";
import utt from "../public/schools/utt.png";

import { useState } from "react";

import Experience from "./components/Experience";
import Education from "./components/Education";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  let image;
  if (darkMode) {
    image = (
      <Image
        alt=""
        src={nichodark}
        fill
        style={{ objectFit: "cover" }}
      />
    );
  } else {
    image = (
      <Image
        alt=""
        src={nicho}
        fill
        style={{ objectFit: "cover" }}
      />
    );
  }

  let emoji1 = darkMode ? "🌙" : "🛠️";
  let emoji2 = darkMode ? "☕" : "👨‍💻";

  return (
    <div className={darkMode ? "dark" : ""}>
      {/* profile */}
      <Head>
        <title>Nicholas Bridgemohan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className=" 
        px-10 md:px-20 lg:px-40 font-robertomono
        bg-slate-50
        dark:bg-slate-800
        "
      >
        <section className="min-h-screen">
          <nav className="py-10 mb-8 flex justify-between dark:fill-white">
            <h1
              className="
              text-transparent bg-clip-text 
              text-xl bg-gradient-to-r
            from-teal-400
            via-blue-300
            to-blue-600
            dark:from-pink-500
            dark:via-blue-500
            dark:to-purple-500          
            background-animate"
            >
              developedbynic
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:fill-white"
                />
              </li>
              <li>
                <a
                  className="
                  text-white px-4 py-2 rounded-md ml-8 bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
                  href="/files/resume.pdf"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2
              className="
            text-4xl py-2 font-medium md:text-6xl text-transparent bg-clip-text 
            bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
            >
              Nicholas Bridgemohan
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-900 dark:text-gray-300">
              Senior Software Engineer {emoji2}
            </h3>
            <p className="text-md py-5 leading-8 md:text-xl  mx-auto  text-gray-800 dark:text-gray-300">
              A results-driven developer skilled in agile development, business intelligence, and technical solutions. Notably led the backend development of the myGGOnline platform, transforming the regional insurance sector. Experienced in API management, cloud services, and database systems, with a strong focus on innovation and client collaboration.

            </p>
          </div>

          <div
            className="
          relative mx-auto rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96
          bg-gradient-to-r
          from-teal-400
          via-blue-300
          to-blue-600
          dark:from-pink-500
          dark:via-blue-500
          dark:to-purple-500          
          background-animate "
          >
            {image}
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 mt-12 text-gray-600">
            {/* <a target="_blank" href="https://twitter.com/sqrpants">
              <AiFillTwitterCircle className="dark:fill-white" />
            </a>

            <a target="_blank" href="https://www.youtube.com/@bridgemohan">
              <AiFillYoutube className="dark:fill-white" />
            </a> */}

            <a target="_blank" href="tel:1-868-279-3914">
              <MdCall className="dark:fill-white" />
            </a>
            <a
              target="_blank"
              href="https://api.whatsapp.com/send?phone=18682793914&text=We%20are%20interested%20in%20meeting%20you!%20%F0%9F%98%80"
            >
              <RiWhatsappFill className="dark:fill-white" />
            </a>
            <a
              target="_blank"
              href="mailto:nbridgemohan@gmail.com?subject=We%20are%20interested%20in%20meeting%20you!%20%F0%9F%98%80"
            >
              <AiFillMail className="dark:fill-white" />
            </a>
            <a target="_blank" href="https://www.linkedin.com/in/bridgemohan/">
              <AiFillLinkedin className="dark:fill-white" />
            </a>
            <a target="_blank" href="https://github.com/nbridgemohan">
              <AiFillGithub className="dark:fill-white" />
            </a> 
                       
          </div>
        </section>

        <section>
          <div className="text-center p-10 pt-60 pb-10">
            <h2
              className="
            text-3xl py-2 font-medium md:text-5xl text-transparent bg-clip-text 
            bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
            >
              Education
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-900 dark:text-gray-300">
              Take a look at my educational background
            </h3>
            <p className="text-md py-5 leading-8 md:text-xl max-w-xl mx-auto  text-gray-800 dark:text-gray-300">
              See the Academic Institutes that I&apos;ve been to
            </p>
          </div>

          <div className="grid sm:grid-cols-1 lg:grid-cols-2 gap-16 justify-center">
            <Education
              time={"September 2008"}
              school={"University of Trinidad and Tobago"}
              certification={"Diploma Computer Information Systems Technology"}
              url={"https://utt.edu.tt/"}
              image={utt}
            />
            <Education
              time={"December 2010"}
              school={"University of Hertfordshire"}
              certification={"B.Sc. Computer Science (Honors)"}
              url={"https://www.herts.ac.uk/"}
              image={uof}
            />
          </div>
        </section>
        {/* experience */}
        <section>
          <div className="text-center p-10 pt-60 pb-10">
            <h2
              className="
            text-3xl py-2 font-medium md:text-5xl text-transparent bg-clip-text 
            bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
            >
              Experience
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-900 dark:text-gray-300">
              10+ Years in Various Industries
            </h3>
            <p className="text-md py-5 leading-8 md:text-xl max-w-xl mx-auto  text-gray-800 dark:text-gray-300">
              Here is a list of my past and current employment
            </p>
          </div>

          <div className="grid sm:grid-cols-1 lg:grid-cols-2 gap-16 justify-center">
            <Experience
              time={"03 / 2024 - Present"}
              company={"Bermudez Group Services Ltd."}
              role={"Systems Solutions Architect"}
              summary={
                "Design, develop, and maintain enterprise applications for payroll, manufacturing, and HR functions across the Bermudez Group of Companies. Upgraded server reporting systems and facilitated data migrations for Holiday Snacks Limited and Bermudez Biscuit Company to new servers. Revamped Django-based payroll systems to facilitate the sending of bonus emails and other data. Created and deployed archive SQL Cubes for OPCOs in the group. Developed and deployed HSE Near Miss application using Laravel."
              }
              techStack={
                "Django, SQL, Laravel, Python, SQL Server"
              }
              skills={"Enterprise Application Development, Data Migration, System Architecture"}
              url={"https://www.bermudezgroup.com"}
              image={bermudez}
            />

            <Experience
              time={"09 / 2021 - 03 / 2024"}
              company={"Evolve Mortgage Services, LLC"}
              role={"Senior Developer"}
              summary={
                "Collaborated with a team of mortgage experts to design and develop solutions for mortgage applications in the United States. Played a key role in the implementation of a Java-based mortgage application solution, enabling providers in the U.S. to process applications efficiently. Developed a Node.js-based application to parse MISMO files and output them in a readable format, significantly improving the team’s efficiency in reviewing mortgage applications."
              }
              techStack={
                "Java, Node.js, MISMO, SQL"
              }
              skills={"Mortgage Application Development, MISMO Parsing, Team Collaboration"}
              url={"https://www.evolvemortgageservices.com"}
              image={evolve}
            />

            <Experience
              time={"12 / 2019 - 08 / 2021"}
              company={"Guardian Group"}
              role={"Full-Stack Developer"}
              summary={
                "Worked with a team to design and develop the front-end and back-end of myGGOnline, an insurance and investments application serving the Caribbean region. Led back-end development, leading two junior developers for the myGGOnline platform, consolidating customer and transactional data across three companies via Azure APIs. Facilitated web-penetration testing of back-end with external vendor and coded patches to fix vulnerabilities. Collaborated with the front-end team to design and code prototypes for a ReactJS-based front-end. Successfully launched an application that provided a real-time portfolio solution, integrating life, health, pension, and mutual fund data in a unified portal."
              }
              techStack={
                "ReactJS, Azure, SQL, Node.js"
              }
              skills={"Full-Stack Development, API Integration, Web Security"}
              url={"https://www.myggonline.com"}
              image={gg}
            />

            <Experience
              time={"05 / 2018 - 12 / 2019"}
              company={"Bermudez Group Services Ltd."}
              role={"Programmer/Analyst"}
              summary={
                "Designed, developed and maintained sales applications across the Bermudez Group of Companies. Launched a new commission reporting system for Bermudez Biscuit Company, enabling on-demand calculations of commissions for salesmen. Developed and implemented an SQL data interface to transfer manufacturing and production data to Dynamics AX daily."
              }
              techStack={
                "SQL, Dynamics AX, .NET"
              }
              skills={"Sales Application Development, Data Interface Implementation, SQL"}
              url={"https://www.bermudezgroup.com"}
              image={bermudez}
            />

            <Experience
              time={"05 / 2017 - 05 / 2018"}
              company={"Ministry of Finance, Treasury Division"}
              role={"Information Systems Specialist"}
              summary={
                "Administered financial reporting and maintained the database for the Trinidad and Tobago Government Payment System. Collaborated with the Comptroller of Accounts to generate financial reports for internal use within the Ministry of Finance. Implemented critical reports reviewed in Parliament by the Minister of Finance."
              }
              techStack={
                "SQL, Financial Reporting, Database Management"
              }
              skills={"Financial Reporting, Database Administration, Government Systems"}
              url={"https://www.finance.gov.tt"}
              image={mofe}
            />

            <Experience
              time={"02 / 2017 - 05 / 2017"}
              company={"Monster Media Group Ltd."}
              role={"Web Developer"}
              summary={
                "Developed websites using WordPress and HTML/CSS/JavaScript in collaboration with graphic designers and social media experts. Designed and developed an insurance brokerage platform using Laravel. Fulfilled client requests for website modifications using WordPress and HTML/CSS/JavaScript."
              }
              techStack={
                "WordPress, HTML/CSS, JavaScript, Laravel"
              }
              skills={"Web Development, Client Collaboration, Platform Development"}
              url={"https://www.monstermediagroup.com"}
              image={monstermedia}
            />

            <Experience
              time={"11 / 2015 - 02 / 2017"}
              company={"Kaizen Environmental Services Trinidad Ltd."}
              role={"Software Developer"}
              summary={
                "Solo developer responsible for designing and developing a company-wide waste inventory management system. Launched a waste inventory management system using only PHP and HTML/CSS/JavaScript, featuring authentication/authorization, barcode reading, and document signing functionalities."
              }
              techStack={
                "PHP, HTML/CSS, JavaScript"
              }
              skills={"Solo Development, Inventory Management, Authentication/Authorization"}
              url={"https://www.kaizenestt.com"}
              image={kaizen}
            />
          </div>
        </section>
        <hr className="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700" />

        {/* contact */}
        {/* <section>
          <div className="text-center p-10 pt-60 pb-10">
            <h2
              className="
            text-3xl py-2 font-medium md:text-5xl text-transparent bg-clip-text 
            bg-gradient-to-r from-teal-400 to-blue-600 dark:bg-gradient-to-r dark:from-pink-400 dark:to-purple-400"
            >
              Contact
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl text-gray-900 dark:text-gray-300">
              Feel Free to reach out!
            </h3>
            <div className="text-5xl flex justify-center gap-16 py-3 mt-12 text-gray-600">
              <a target="_blank" href="tel:1-868-279-3914">
                <BsPhone className="dark:fill-white" />
              </a>
              <a
                target="_blank"
                href="https://api.whatsapp.com/send?phone=18682793914&text=We%20are%20interested%20in%20meeting%20you!%20%F0%9F%98%80"
              >
                <BsWhatsapp className="dark:fill-white" />
              </a>
              <a
                target="_blank"
                href="mailto:nbridgemohan@gmail.com?subject=We%20are%20interested%20in%20meeting%20you!%20%F0%9F%98%80"
              >
                <AiOutlineMail className="dark:fill-white" />
              </a>
            </div>
          </div>
        </section> */}
        <footer>
          <div className="text-center">
            <p>&#169; 2025 Nicholas Bridgemohan</p>
          </div>
        </footer>
      </main>
    </div>
  );
}
